### ISSUE TITLE
Il rover non si muove allo "START" se una startingDistance iniziale non viene impostata

### ISSUE THREAD

**Issue by Luxor001** [Robotex/ISS-Final-Task-1617#1]
CDT, per riprodurre:

1. far partire unity e l'applicazione
2. connectToUnity("...")
3. premere start sulla GUI utente

il robot si girerà verso la giusta direzione, ma non si allontanerà dalla linea del sonar

**Comment by piaga** [comment]
Credo di aver risolto ma nel dubbio controllate e poi chiudete il thread
