### ISSUE TITLE
Non è possibile impostare cambi di distance <= 5 prima della partenza

### ISSUE THREAD

**Issue by Luxor001** [Robotex/ISS-Final-Task-1617#11]
CDT, ad esempio inserendo 
setStartDistance(15)
setStartDistance(20)
setStartDistance(25)

non si vedrà alcuno spostamento del robot tra 15 e 20, ma all'inserimento di 25 sì.
In altre parole, sembra che il robot percepisca cambiamenti soltanto di 10 unità alla volta.

**Comment by piaga** [comment]
può essere dovuto dal treshold impostato da J

**Comment by Luxor001** [comment]
È molto probabile infatti.
@Robotex a cosa servono esattamente LOWERTRESHOLD e UPPERTRESHOLD, presenti verso riga ~60 di testRover4.qa?

**Comment by Robotex** [comment]
servono a memorizzare i valori inferiori e superiori delle operazioni minus/plus con costante 5 (numero empirico), quindi se distanza è impostata a 10 il segmento in cui si fermerà sarà compreso tra 5 e 15

**Comment by Luxor001** [comment]
Chiuso da commit 8685b75, impostando un treshold minimo di 2
