### ISSUE TITLE
Talvolta il robot và indietro indefinitivamente alla partenza

### ISSUE THREAD

**Issue by Luxor001** [Robotex/ISS-Final-Task-1617#12]
CDT, non ho trovato un modo univoco e affidabile per replicare il problema ma si è già presentato 2 volte su un totale di 6-7 prove.
In sostanza, dopo aver impostato la distanza con setStartDistance() e aver premuto START, il robot và indietro piuttosto che avanti verso il sonar 2.

**Comment by Luxor001** [comment]
Il problema è riproducibile ogniqualvolta che si eseguono i seguenti passi: 

1. connectToUnity()
2. setStartDistance(10)
3. START

**Comment by piaga** [comment]
testo subito anche io per conferma,
comincio a dubitare dell'affidabilità dei movimenti imposti in questo modo

**Comment by Luxor001** [comment]
Chiuso da commit 8685b75c9db3a28a955b889c77ed03d3f5c88818
